django-autorecruiting-app/autorecruiting/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index),
    re_path(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('login/', views.login_view, name='login'),
    path('candidate-information/messenger/<int:id>', views.candidate_information_messenger, name='candidate-main'),
    path('candidate-information/main/<int:id>', views.candidate_information_main, name='candidate-messenger'),
    path('candidates/', views.candidates, name='candidates'),
    path('find-candidates/', views.find_candidates, name='find-candidates'),
    path('candidates-by-vacancy-id/<int:id>', views.candidates_by_vacancy_id, name='candidates-by-vacancy-id'),
    path('add-vacancy/', views.add_vacancy, name='add-vacancy'),
    path('edit-vacancy/<int:id>', views.edit_vacancy, name='edit-vacancy'),
    # path('search-resumes/', views.search_resumes, name='search-resumes'),
    path('vacancy-edit-add/', views.vacancy_edit_add, name='add-edit-post-vacancy'),
    path('hr/statistics/', views.error_500, name='add-edit-post-vacancy'),
    path('hr-edit-add/', views.hr_edit_add, name='add-edit-post-hr'),
    # path('hr/add/', views.add_hr, name='add-hr'),
    path('hr/edit-by-id/<int:id>', views.edit_hr_by_id, name='edit-hr-by-id'),

    path('hr/all/', views.hr_all, name='hr-all'),

    path('hr/archive-vacancies/', views.hr_archive_vacancies, name='hr-archive-vacancies'),
    path('hr/vacancies/', views.hr_vacancies, name='hr-vacancies'),

    path('hr/<int:id>/own-vacancies/', views.hr_own_vacancies, name='hr-by-id-own-vacancies'),
    path('hr/statistics/', views.hr_statistics, name='hr-statistics'),
    path('vacancy-information/<int:id>', views.vacancy_information, name='vacancy-information'),
    path('hr/messenger/hr/<int:id>', views.hr_messenger_to_hrbp, name='hr-messenger-hrbp'),
    # path('hr/messenger/customer/<int:id>', views.hr_messenger_to_customer, name='hr-messenger-customer'),
    path('hr/messenger/candidate/<int:id>', views.hr_messenger_to_candidate, name='hrs-messenger-candidate'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-autorecruiting-app/django-autorecruiting-app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),   # for documentation
    path('admin/', admin.site.urls),
    path('', include('autorecruiting.urls'))
]

django-autorecruiting-app/autorecruiting/models.py
import sched
import time
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import (Model)

s = sched.scheduler(time.time, time.sleep)


class CustomUser(AbstractUser):
    is_HR = models.BooleanField(default=False)
    is_HRBP = models.BooleanField(default=False)
    is_Customer = models.BooleanField(default=False)
    patronymic = models.CharField(max_length=31, blank=True)
    phone = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.last_name + self.first_name + self.patronymic


EMPLOYMENT_TYPE_CHOICES = [
    (0, 'Полная занятость'),
    (1, 'Стажировка'),
    (2, 'Частичная занятость'),
]

WORK_SCHEDULE_CHOICES = [
    (0, 'Полный день'),
    (1, 'Удалённая работа'),
    (2, 'Гибкий график'),
]

EDUCATION_CHOICES = [
    (0, 'Основное общее'),
    (1, 'Среднее общее'),
    (2, 'Среднее профессиональное'),
    (3, 'Неоконченное высшее'),
    (4, 'Бакалавр'),
    (5, 'Магистр'),
]
INTERVIEW_STATUS_CHOICES = [
    (0, 'Назначено'),
    (1, 'Проведено успешно'),
    (2, 'Отказ')
]
TEST_TASK_STATUS_CHOICES = [
    (0, 'Отправлено кандидату'),
    (1, 'На проверке'),
    (2, 'Принято'),
    (3, 'Отказ'),
]
CANDIDATE_STATUS_CHOICES = [
    (0, 'Не выбран'),
    (1, 'Выбран'),
    (2, 'Тестовое задание'),
    (3, 'Интервью c hr'),
    (4, 'Техническое интревью'),
    (5, 'Выслан оффер'),
    (6, 'Отказ'),  # До какого момента отслеживается кандидат?
]


class VisitedCandidate(models.Model):
    idExternalService = models.IntegerField()


class Speciality(models.Model):
    specialityName = models.CharField(max_length=127)

    def __str__(self):
        return self.specialityName


class Country(models.Model):
    countryName = models.CharField(max_length=31)

    def __str__(self):
        return self.countryName


class City(models.Model):
    cityName = models.CharField(max_length=31)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.cityName + ', ' + self.country.__str__()


class Customer(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    nameOfCompany = models.CharField(max_length=31, default="SuperCompany")
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)


class HRBP(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)


class HR(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    hRBP = models.ForeignKey(HRBP, on_delete=models.CASCADE, null=True, blank=True)


class Vacancy(models.Model):
    chosenLetter = models.TextField(default="")

    speciality = models.ForeignKey(Speciality, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=127)

    hR = models.ForeignKey(HR, on_delete=models.SET_NULL, null=True)
    hRBP = models.ForeignKey(HRBP, on_delete=models.CASCADE, null=True, blank=True)

    employmentType = models.IntegerField(choices=EMPLOYMENT_TYPE_CHOICES, default=EMPLOYMENT_TYPE_CHOICES)
    workSchedule = models.IntegerField(choices=WORK_SCHEDULE_CHOICES, default=WORK_SCHEDULE_CHOICES)
    vacancyDescription = models.CharField(max_length=2047)

    workExperienceFrom = models.IntegerField(default=1)
    workExperienceTo = models.IntegerField(default=3)

    suggestedSalaryFrom = models.IntegerField(default=200000)
    suggestedSalaryTo = models.IntegerField(default=500000)

    educationLevel = models.IntegerField(choices=EDUCATION_CHOICES)
    isArchived = models.BooleanField(default=False)  # заменить на статус

    testTaskDescription = models.TextField(default="")
    testTaskLink = models.CharField(max_length=127)
    testTaskLetter = models.TextField(default="")


class Candidate(models.Model):
    # vacancies = models.ManyToManyField(Vacancy,  null=True)

    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    speciality = models.ForeignKey(Speciality, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=31)
    surname = models.CharField(max_length=31)
    patronymic = models.CharField(max_length=31, blank=True)
    email = models.CharField(max_length=31)
    phone = models.CharField(max_length=10, blank=True)
    birthdayDate = models.DateField()
    resumeLink = models.CharField(max_length=255)
    workExperienceDuration = models.IntegerField()
    relocationReady = models.BooleanField()
    expectedSalaryFrom = models.IntegerField()
    expectedSalaryTo = models.IntegerField()
    educationLevel = models.IntegerField(choices=EDUCATION_CHOICES)


class Message(Model):
    sender = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(default="")
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __init__(self, body,  subject="",   *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.subject = subject
        self.body = body

        # send_mail(
        #     body=body
        #     subject=subject,
        #     sender.email,
        #     recipient.email,
        #     fail_silently=False
        # )

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']


class Interview(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(default=datetime(1970, 1, 1))
    interviewer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(choices=CANDIDATE_STATUS_CHOICES, default=CANDIDATE_STATUS_CHOICES)

    def __init__(self, interviewer, date, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.date = date
        self.interviewer = interviewer
        self.status = 0
        if self.interviewer.is_Customer:
            vac = VacancyCandidate.objects.get(interviewCustomer=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewCustomer=self).get_candidate()
            type = 'Техническое собеседование'
        else:
            vac = VacancyCandidate.objects.get(interviewHR=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewHR=self).get_candidate()
            type = 'Собеседование с hr'
        Message(email=candidate.email,
                name=candidate.name,
                sender=self.interviewer,
                body=f"Назначено {type} кандидату "
                     f"{candidate.name} {candidate.surname}"
                     f"по вакансии {vac.get_name()}."
                     f"День интервью: {self.date}.",
                subject=f"Назначено {type}  c {self.interviewer}"
                        f"{vac.get_name()}").save()

    def set_accepted(self, comment):
        self.status = 1
        self.comment = comment
        if self.interviewer.is_Customer:
            vac = VacancyCandidate.objects.get(interviewCustomer=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewCustomer=self).get_candidate()
            type = 'Техническое собеседование'
        else:
            vac = VacancyCandidate.objects.get(interviewHR=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewHR=self).get_candidate()
            type = 'Собеседование с hr'
        Message(email=candidate.email,
                name=candidate.name,
                sender=self.interviewer,
                body=f"{type} с кандидатом"
                     f"{candidate.name} {candidate.surname}"
                     f"по вакансии {vac.get_name()}"
                     f"по следующей причине: {comment}",
                subject=f"Успешное Интервью по вакансии "
                        f"{vac.get_name()}").save()
        if self.interviewer.is_Customer:
            VacancyCandidate.objects.get(interviewCustomer=self).send_offer(self.interviewer)

    def set_not_accepted(self, comment):
        self.status = 2
        self.comment = comment
        if self.interviewer.is_Customer:
            VacancyCandidate.objects.get(interviewCustomer=self).set_status(6)
            vac = VacancyCandidate.objects.get(interviewCustomer=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewCustomer=self).get_candidate()
            type = 'Техническое собеседование'
        else:
            VacancyCandidate.objects.get(interviewHR=self).set_status(6)
            vac = VacancyCandidate.objects.get(interviewHR=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewHR=self).get_candidate()
            type = 'Собеседование с hr'
        Message(email=candidate.email,
                name=candidate.name,
                sender=self.interviewer,
                body=f"{type} с кандидатом"
                     f"{candidate.name} {candidate.surname}"
                     f"по вакансии {vac.get_vacancy().get_name()}"
                     f"по следующей причине: {comment}",
                subject=f"Отказ Интервью по вакансии "
                        f"{vac.get_name()}").save()

    def get_interview_date(self):
        return self.date.strftime("%Y-%m-%d")


class TestTask(models.Model):
    letter_for_candidate = models.TextField(default="")
    task = models.TextField(default="")
    link = models.CharField(max_length=255)
    startDate = models.DateTimeField(auto_now_add=True)
    finishDate = models.DateTimeField(default=datetime(1970, 1, 1))

django-autorecruiting-app/autorecruiting/forms.py
from django import forms
from .models import City, Speciality, EDUCATION_CHOICES, WORK_SCHEDULE_CHOICES, EMPLOYMENT_TYPE_CHOICES


class VacancyForm(forms.Form):
    name = forms.CharField(strip=True)
    vacancyDescription = forms.CharField(widget=forms.Textarea)
    testTaskDescription = forms.CharField(widget=forms.Textarea)
    testTaskLink = forms.CharField(strip=True)
    chosenLetter = forms.CharField(widget=forms.Textarea)
    testTaskLetter = forms.CharField(widget=forms.Textarea)
    educationLevel = forms.ChoiceField(choices=EDUCATION_CHOICES)
    employmentType = forms.ChoiceField(choices=EMPLOYMENT_TYPE_CHOICES)
    workSchedule = forms.ChoiceField(choices=WORK_SCHEDULE_CHOICES)
    workExperienceFrom = forms.IntegerField(step_size=1, min_value=12000)
    workExperienceTo = forms.IntegerField(step_size=1, min_value=12000)
    suggestedSalaryFrom = forms.IntegerField(step_size=1000, min_value=10000)
    suggestedSalaryTo = forms.IntegerField(step_size=1000, min_value=10000)
    city = forms.ChoiceField(choices=[(o.id, str(o)) for o in City.objects.all()])
    speciality = forms.ChoiceField(choices=[(o.id, str(o)) for o in Speciality.objects.all()])

django-autorecruiting-app/autorecruiting/templates/basic/vacancy/list-of-vacancies.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/vacancy/list-of-vacancies.css' %}">
<script src="https://kit.fontawesome.com/98db032af2.js" crossorigin="anonymous"></script>
<div class="vacancy-module">
    <form>
        <input type="text" placeholder="Поиск по вакансиям">
        <a><button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button></a>
        <a href="/add-vacancy/"><div>Добавить вакансию</div></a>
    </form>
    <div class="vacancy-list">
        {% for vacancy in vacancies %}
        {% include "basic/vacancy/vacancy-card.html" with vacancy=vacancy %}
        {% endfor %}
    </div>

</div>

django-autorecruiting-app/autorecruiting/templates/basic/vacancy/vacancy-card.html
{% load static %}
{% load custom_filters %}
<link rel="stylesheet" type="text/css" href="{% static 'css/vacancy/vacancy-card.css' %}">
{% if not vacancy.isArchived %}
<div class="vacancy-card-small">
{% else %}
<div class="vacancy-card-small archived">
{% endif %}
    <div class="vacancy-info-small">
        <div class="vacancy-header-small">
                {{ vacancy.name }}
        </div>
        <div>
            <span>Специальность:</span>
            <span>{{ vacancy.speciality.specialityName}}</span>
        </div>
        <div>
            <span>Локация:</span>
            <span>{{ vacancy.city.cityName}}, {{ vacancy.city.country.countryName}}</span>
        </div>
        <div>
            <span>Опыт работы:</span>
            <span>{{ vacancy.workExperienceFrom }}-{{ vacancy.workExperienceTo }}</span>
        </div>
        <div>
            <span>Требования:</span>
            <span>{{ vacancy.get_educationLevel_display}}</span>
        </div>
    </div>

    {% if user.is_HRBP %}
    <div class="vacancy-hr">
        <span>
            Назначен:
        </span>
        <span>
           {{ vacancy.hR.user.username }}
        </span>
    </div>

    {% endif %}
    <a href="/vacancy-information/{{ vacancy.id }}"><div>Подробнее</div></a>
</div>

django-autorecruiting-app/autorecruiting/templates/basic/vacancy/vacancy-form.html
{% load custom_filters %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/vacancy/form.css' %}">

{% if  vacancy.isArchived %}
<div class="vacancy-card archived">
    {% else %}
<div class="vacancy-card">
{% endif %}
    <form class="panel-manage" method="post" action="/vacancy-edit-add/">
    {% csrf_token %}
    <div class="vacancy-info">
    {{ form.as_div }}
{#    TODO add city to vacancy#}
{#            <div class="vacancy-header">#}
{#                <label for="vacancy-name">Вакансия № {{ vacancy.id }}:</label>#}
{#                <input type="text" name="name" value="{{ vacancy.name }}">#}
{#                <input name="id" type="text" value="{{ vacancy.id }}" hidden>#}
{#           </div>#}
{#        <div class="vacancy-desc">#}
{##}
{#            <label for="vacancy-desc">Описание</label>#}
{#            <textarea name="vacancyDescription">{{ vacancy.vacancyDescription }}</textarea>#}
{##}
{#            <label for="vacancy-desc-task">Тествое задание</label>#}
{#            <textarea name="testTaskDescription" placeholder="Письмо к заданию">{{ vacancy.testTaskDescription }}</textarea>#}
{#            <input type="text" placeholder="Ссылка на задание" name="testTaskLink" value="{{ vacancy.testTaskLink }}">#}
{##}
{#            <div>#}
{#                <label>Зарплата от </label>#}
{#                <input type="number" value="{{ vacancy.suggestedSalaryFrom }}" name="suggestedSalaryFrom">#}
{#                <label> до </label>#}
{#                <input type="number" value="{{ vacancy.suggestedSalaryTo }}" name="suggestedSalaryTo">#}
{#            </div>#}
{##}
{#            <div>#}
{#                <label>Опыт работы от </label>#}
{#                <input type="number" value="{{ vacancy.workExperienceFrom }}" name="workExperienceFrom">#}
{#                <label> до </label>#}
{#                <input type="number" value="{{ vacancy.workExperienceTo }}" name="workExperienceTo">#}
{#            </div>#}
{#            <div>#}
{#                <label>Образование</label>#}
{#                <select name="educationLevel">#}
{#                    {% if vacancy %}#}
{#                        <option value="{{ vacancy.educationLevel }}">{{ vacancy.get_educationLevel_display }}</option>#}
{#                        {% endif %}#}
{#                        {% for e in EDUCATION_CHOICES %}#}
{#                            {% if e != vacancy.educationLevel %}#}
{#                                {% if e == 0 %}#}
{#                                    <option value={{ e }}>Основное общее</option>#}
{#                                {% elif e == 1%}#}
{#                                    <option value={{ e }}>Среднее общее</option>#}
{#                                    {% elif e == 2%}#}
{#                                    <option value={{ e }}>Среднее профессиональное</option>#}
{#                                    {% elif e == 3%}#}
{#                                    <option value={{ e }}>Неоконченное высшее</option>#}
{#                                    {% elif e == 4%}#}
{#                                    <option value={{ e }}>Бакалавр</option>#}
{#                                 {% else %}#}
{#                                    <option value={{ e }}>Магистр</option>#}
{#                                {% endif %}#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                </select>#}
{#            </div>#}
{##}
{#             <div>#}
{#                <label>График работы</label>#}
{#                <select name="workSchedule">#}
{#                    {% if vacancy %}#}
{#                        <option value="{{ vacancy.workSchedule }}">{{ vacancy.get_workSchedule_display }}</option>#}
{#                        {% endif %}#}
{#                        {% for e in WORK_SCHEDULE_CHOICES %}#}
{#                            {% if e != vacancy.workSchedule %}#}
{#                                {% if e == 0 %}#}
{#                                    <option value={{ e }}>Полный день</option>#}
{#                                {% elif e == 1%}#}
{#                                    <option value={{ e }}>Удалённая работа</option>#}
{#                                 {% else %}#}
{#                                    <option value={{ e }}>Гибкий график</option>#}
{#                                {% endif %}#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{##}
{#                </select>#}
{#            </div>#}
{#             <div>#}
{#                    <label>Тип занятости</label>#}
{#                    <select name="employmentType">#}
{#                        {% if vacancy %}#}
{#                        <option value="{{ vacancy.employmentType }}">{{ vacancy.get_employmentType_display }}</option>#}
{#                        {% endif %}#}
{#                        {% for e in EMPLOYMENT_TYPE_CHOICES %}#}
{#                            {% if e != vacancy.employmentType %}#}
{#                                {% if e == 0 %}#}
{#                                    <option value={{ e }}>Полная занятость</option>#}
{#                                {% elif e == 1%}#}
{#                                    <option value={{ e }}>Стажировка</option>#}
{#                                 {% else %}#}
{#                                    <option value={{ e }}>Частичная занятость</option>#}
{#                                {% endif %}#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                </div>#}
{#                <div>#}
{#                    <label>Локация</label>#}
{#                    <select name="city">#}
{#                        {% if vacancy %}#}
{#                        <option value="{{ vacancy.city.id }}">{{ vacancy.city.cityName }}, {{ vacancy.city.country.countryName }} </option>#}
{#                        {% endif %}#}
{#                        {% for city in cities %}#}
{#                            {% if city.id != vacancy.city.id %}#}
{#                            <option value={{ city.id }}>{{ city.cityName }}, {{ city.country.countryName }}</option>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                </div>#}
{#            <div>#}
{#                    <label>Специальность</label>#}
{#                    <select name="speciality">#}
{#                        {% if vacancy %}#}
{#                        <option value="{{ vacancy.speciality.id }}">{{ vacancy.speciality.specialityName }}</option>#}
{#                        {% endif %}#}
{#                        {% for speciality in specialities%}#}
{#                            {% if speciality.id != vacancy.speciality.id %}#}
{#                            <option value={{ speciality.id }}>{{ speciality.specialityName }}</option>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                </div>#}
{##}
{#            <div>#}
{#                {% if user.is_HRBP and hrs %}#}
{#                    <label for="select-hr">Назначить hr</label>#}
{##}
{#                    <select name="hR">#}
{#                       {% if vacancy.hR %}#}
{#                           <option value="{{ vacancy.hR.id }}">{{vacancy.hR.user.username}}</option>#}
{#                        {% else %}#}
{#                           <option value="">Назначить hr</option>#}
{#                        {% endif %}#}
{##}
{#                        {% for hr in hrs %}#}
{#                            {% if vacancy.hR.id != hr.id %}#}
{#                            <option value={{ hr.id }}>{{ hr.user.username }}</option>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#                    </select>#}
{##}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
{##}
{##}
{#    </div>#}
    <div class="buttons-holder">
       {% if  vacancy.isArchived %}
<button type="submit" name="archive_out">
                Вернуть из архива
       </button>
    {% else %}
    <button type="submit" name="save" id="save">
                <i class="fa fa-check" aria-hidden="true"></i>
       </button>
        <button type="submit" name="archive_into">
            <i class="fa fa-archive" aria-hidden="true"></i>
        </button>
{% endif %}

    </div>
    </form>
</div>

django-autorecruiting-app/autorecruiting/templates/basic/vacancy/vacancy.html
{% load custom_filters %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/vacancy/vacancy.css' %}">
{% if  vacancy.isArchived %}
<div class="vacancy-card archived">
    {% else %}
<div class="vacancy-card">
{% endif %}
{#    TODO add city to vacancy#}
    <div class="vacancy-info">
        <div class="vacancy-header">
            <span>
                Вакансия № {{ vacancy.id }}:
            </span>
            <span>
                {{ vacancy.name }}
            </span>
        </div>
        <dl class="vacancy-desc">
            <dt>Локация:</dt>
            <dd>{{ vacancy.city.cityName}}, {{ vacancy.city.country.countryName}}</dd>

            <dt>Специальность:</dt>
            <dd>{{ vacancy.speciality.specialityName}}</dd>

            <dt>Задачи:</dt>
            <dd>
                {{ vacancy.get_workSchedule_display }}
            </dd>
            <dt>Требования:</dt>
            <dd>
                {{ vacancy.get_educationLevel_display}}; опыт работы от {{ vacancy.workExperienceFrom|display_months }} до {{ vacancy.workExperienceTo|display_months }}.
            </dd>
            <dt>Условия:</dt>
            <dd>
                {{ vacancy.get_employmentType_display }}, зарплата от {{ vacancy.suggestedSalaryFrom }}руб до {{ vacancy.suggestedSalaryTo }}руб.
            </dd>
            <dt>Описание:</dt>
            <dd>
                 {{ vacancy.vacancyDescription }}
            </dd>
            <dt>Тествое задание</dt>
            <dd>
                {{ vacancy.testTaskDescription }}
            </dd>
            <dd>
                <a href="{{ vacancy.testTaskLink }}">{{ vacancy.testTaskLink }}</a>
            </dd>
        </dl>
        {% if user.is_HRBP %}
            <div>
                <span>
                    Назначен:
                </span>
                <span>
                    {{ vacancy.hR.user.username }}
                </span>
            </div>
        {% endif %}
    {% if  vacancy.isArchived %}
        <div>
        В архиве
        </div>
    {% endif %}


    </div>
    <div class="vacancy-manage-panel">
        {% if not vacancy.isArchived %}
            <a href="/candidates-by-vacancy-id/{{ vacancy.id }}" ><div>Подбор кандидата</div></a>


    {% endif %}
{#        TODO add statistic page#}
        <a href="/hr/statistics/"><div>Статистика</div></a>
        <a  href="/edit-vacancy/{{ vacancy.id }}"><div>Редактировать</div></a>





    </div>
</div>