django-autorecruiting-app/autorecruiting/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index),
    re_path(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('login/', views.login_view, name='login'),
    path('candidate-information/messenger/<int:id>', views.candidate_information_messenger, name='candidate-main'),
    path('candidate-information/main/<int:id>', views.candidate_information_main, name='candidate-messenger'),
    path('candidates/', views.candidates, name='candidates'),
    path('find-candidates/', views.find_candidates, name='find-candidates'),
    path('candidates-by-vacancy-id/<int:id>', views.candidates_by_vacancy_id, name='candidates-by-vacancy-id'),
    path('add-vacancy/', views.add_vacancy, name='add-vacancy'),
    path('edit-vacancy/<int:id>', views.edit_vacancy, name='edit-vacancy'),
    # path('search-resumes/', views.search_resumes, name='search-resumes'),
    path('vacancy-edit-add/', views.vacancy_edit_add, name='add-edit-post-vacancy'),
    path('hr/statistics/', views.error_500, name='add-edit-post-vacancy'),
    path('hr-edit-add/', views.hr_edit_add, name='add-edit-post-hr'),
    # path('hr/add/', views.add_hr, name='add-hr'),
    path('hr/edit-by-id/<int:id>', views.edit_hr_by_id, name='edit-hr-by-id'),

    path('hr/all/', views.hr_all, name='hr-all'),

    path('hr/archive-vacancies/', views.hr_archive_vacancies, name='hr-archive-vacancies'),
    path('hr/vacancies/', views.hr_vacancies, name='hr-vacancies'),

    path('hr/<int:id>/own-vacancies/', views.hr_own_vacancies, name='hr-by-id-own-vacancies'),
    path('hr/statistics/', views.hr_statistics, name='hr-statistics'),
    path('vacancy-information/<int:id>', views.vacancy_information, name='vacancy-information'),
    path('hr/messenger/hr/<int:id>', views.hr_messenger_to_hrbp, name='hr-messenger-hrbp'),
    # path('hr/messenger/customer/<int:id>', views.hr_messenger_to_customer, name='hr-messenger-customer'),
    path('hr/messenger/candidate/<int:id>', views.hr_messenger_to_candidate, name='hrs-messenger-candidate'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-autorecruiting-app/django-autorecruiting-app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),   # for documentation
    path('admin/', admin.site.urls),
    path('', include('autorecruiting.urls'))
]

django-autorecruiting-app/autorecruiting/models.py
import sched
import time
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import (Model)

s = sched.scheduler(time.time, time.sleep)


class CustomUser(AbstractUser):
    is_HR = models.BooleanField(default=False)
    is_HRBP = models.BooleanField(default=False)
    is_Customer = models.BooleanField(default=False)
    patronymic = models.CharField(max_length=31, blank=True)
    phone = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.last_name + self.first_name + self.patronymic


EMPLOYMENT_TYPE_CHOICES = [
    (0, 'Полная занятость'),
    (1, 'Стажировка'),
    (2, 'Частичная занятость'),
]

WORK_SCHEDULE_CHOICES = [
    (0, 'Полный день'),
    (1, 'Удалённая работа'),
    (2, 'Гибкий график'),
]

EDUCATION_CHOICES = [
    (0, 'Основное общее'),
    (1, 'Среднее общее'),
    (2, 'Среднее профессиональное'),
    (3, 'Неоконченное высшее'),
    (4, 'Бакалавр'),
    (5, 'Магистр'),
]
INTERVIEW_STATUS_CHOICES = [
    (0, 'Назначено'),
    (1, 'Проведено успешно'),
    (2, 'Отказ')
]
TEST_TASK_STATUS_CHOICES = [
    (0, 'Отправлено кандидату'),
    (1, 'На проверке'),
    (2, 'Принято'),
    (3, 'Отказ'),
]
CANDIDATE_STATUS_CHOICES = [
    (0, 'Не выбран'),
    (1, 'Выбран'),
    (2, 'Тестовое задание'),
    (3, 'Интервью c hr'),
    (4, 'Техническое интревью'),
    (5, 'Выслан оффер'),
    (6, 'Отказ'),  # До какого момента отслеживается кандидат?
]


class VisitedCandidate(models.Model):
    idExternalService = models.IntegerField()


class Speciality(models.Model):
    specialityName = models.CharField(max_length=127)

    def __str__(self):
        return self.specialityName


class Country(models.Model):
    countryName = models.CharField(max_length=31)

    def __str__(self):
        return self.countryName


class City(models.Model):
    cityName = models.CharField(max_length=31)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.cityName + ', ' + self.country.__str__()


class Customer(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    nameOfCompany = models.CharField(max_length=31, default="SuperCompany")
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)


class HRBP(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)


class HR(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    hRBP = models.ForeignKey(HRBP, on_delete=models.CASCADE, null=True, blank=True)


class Vacancy(models.Model):
    chosenLetter = models.TextField(default="")

    speciality = models.ForeignKey(Speciality, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=127)

    hR = models.ForeignKey(HR, on_delete=models.SET_NULL, null=True)
    hRBP = models.ForeignKey(HRBP, on_delete=models.CASCADE, null=True, blank=True)

    employmentType = models.IntegerField(choices=EMPLOYMENT_TYPE_CHOICES, default=EMPLOYMENT_TYPE_CHOICES)
    workSchedule = models.IntegerField(choices=WORK_SCHEDULE_CHOICES, default=WORK_SCHEDULE_CHOICES)
    vacancyDescription = models.CharField(max_length=2047)

    workExperienceFrom = models.IntegerField(default=1)
    workExperienceTo = models.IntegerField(default=3)

    suggestedSalaryFrom = models.IntegerField(default=200000)
    suggestedSalaryTo = models.IntegerField(default=500000)

    educationLevel = models.IntegerField(choices=EDUCATION_CHOICES)
    isArchived = models.BooleanField(default=False)  # заменить на статус

    testTaskDescription = models.TextField(default="")
    testTaskLink = models.CharField(max_length=127)
    testTaskLetter = models.TextField(default="")


class Candidate(models.Model):
    # vacancies = models.ManyToManyField(Vacancy,  null=True)

    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    speciality = models.ForeignKey(Speciality, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=31)
    surname = models.CharField(max_length=31)
    patronymic = models.CharField(max_length=31, blank=True)
    email = models.CharField(max_length=31)
    phone = models.CharField(max_length=10, blank=True)
    birthdayDate = models.DateField()
    resumeLink = models.CharField(max_length=255)
    workExperienceDuration = models.IntegerField()
    relocationReady = models.BooleanField()
    expectedSalaryFrom = models.IntegerField()
    expectedSalaryTo = models.IntegerField()
    educationLevel = models.IntegerField(choices=EDUCATION_CHOICES)


class Message(Model):
    sender = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(default="")
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __init__(self, body,  subject="",   *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.subject = subject
        self.body = body

        # send_mail(
        #     body=body
        #     subject=subject,
        #     sender.email,
        #     recipient.email,
        #     fail_silently=False
        # )

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']


class Interview(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(default=datetime(1970, 1, 1))
    interviewer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(choices=CANDIDATE_STATUS_CHOICES, default=CANDIDATE_STATUS_CHOICES)

    def __init__(self, interviewer, date, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.date = date
        self.interviewer = interviewer
        self.status = 0
        if self.interviewer.is_Customer:
            vac = VacancyCandidate.objects.get(interviewCustomer=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewCustomer=self).get_candidate()
            type = 'Техническое собеседование'
        else:
            vac = VacancyCandidate.objects.get(interviewHR=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewHR=self).get_candidate()
            type = 'Собеседование с hr'
        Message(email=candidate.email,
                name=candidate.name,
                sender=self.interviewer,
                body=f"Назначено {type} кандидату "
                     f"{candidate.name} {candidate.surname}"
                     f"по вакансии {vac.get_name()}."
                     f"День интервью: {self.date}.",
                subject=f"Назначено {type}  c {self.interviewer}"
                        f"{vac.get_name()}").save()

    def set_accepted(self, comment):
        self.status = 1
        self.comment = comment
        if self.interviewer.is_Customer:
            vac = VacancyCandidate.objects.get(interviewCustomer=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewCustomer=self).get_candidate()
            type = 'Техническое собеседование'
        else:
            vac = VacancyCandidate.objects.get(interviewHR=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewHR=self).get_candidate()
            type = 'Собеседование с hr'
        Message(email=candidate.email,
                name=candidate.name,
                sender=self.interviewer,
                body=f"{type} с кандидатом"
                     f"{candidate.name} {candidate.surname}"
                     f"по вакансии {vac.get_name()}"
                     f"по следующей причине: {comment}",
                subject=f"Успешное Интервью по вакансии "
                        f"{vac.get_name()}").save()
        if self.interviewer.is_Customer:
            VacancyCandidate.objects.get(interviewCustomer=self).send_offer(self.interviewer)

    def set_not_accepted(self, comment):
        self.status = 2
        self.comment = comment
        if self.interviewer.is_Customer:
            VacancyCandidate.objects.get(interviewCustomer=self).set_status(6)
            vac = VacancyCandidate.objects.get(interviewCustomer=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewCustomer=self).get_candidate()
            type = 'Техническое собеседование'
        else:
            VacancyCandidate.objects.get(interviewHR=self).set_status(6)
            vac = VacancyCandidate.objects.get(interviewHR=self).get_vacancy()
            candidate = VacancyCandidate.objects.get(interviewHR=self).get_candidate()
            type = 'Собеседование с hr'
        Message(email=candidate.email,
                name=candidate.name,
                sender=self.interviewer,
                body=f"{type} с кандидатом"
                     f"{candidate.name} {candidate.surname}"
                     f"по вакансии {vac.get_vacancy().get_name()}"
                     f"по следующей причине: {comment}",
                subject=f"Отказ Интервью по вакансии "
                        f"{vac.get_name()}").save()

    def get_interview_date(self):
        return self.date.strftime("%Y-%m-%d")


class TestTask(models.Model):
    letter_for_candidate = models.TextField(default="")
    task = models.TextField(default="")
    link = models.CharField(max_length=255)
    startDate = models.DateTimeField(auto_now_add=True)
    finishDate = models.DateTimeField(default=datetime(1970, 1, 1))

django-autorecruiting-app/autorecruiting/forms.py
from django import forms
from .models import City, Speciality, EDUCATION_CHOICES, WORK_SCHEDULE_CHOICES, EMPLOYMENT_TYPE_CHOICES


class VacancyForm(forms.Form):
    name = forms.CharField(strip=True)
    vacancyDescription = forms.CharField(widget=forms.Textarea)
    testTaskDescription = forms.CharField(widget=forms.Textarea)
    testTaskLink = forms.CharField(strip=True)
    chosenLetter = forms.CharField(widget=forms.Textarea)
    testTaskLetter = forms.CharField(widget=forms.Textarea)
    educationLevel = forms.ChoiceField(choices=EDUCATION_CHOICES)
    employmentType = forms.ChoiceField(choices=EMPLOYMENT_TYPE_CHOICES)
    workSchedule = forms.ChoiceField(choices=WORK_SCHEDULE_CHOICES)
    workExperienceFrom = forms.IntegerField(step_size=1, min_value=12000)
    workExperienceTo = forms.IntegerField(step_size=1, min_value=12000)
    suggestedSalaryFrom = forms.IntegerField(step_size=1000, min_value=10000)
    suggestedSalaryTo = forms.IntegerField(step_size=1000, min_value=10000)
    city = forms.ChoiceField(choices=[(o.id, str(o)) for o in City.objects.all()])
    speciality = forms.ChoiceField(choices=[(o.id, str(o)) for o in Speciality.objects.all()])

django-autorecruiting-app/autorecruiting/templates/basic/candidate/candidate-main.html
{% load static %}
{% load custom_filters %}

<link rel="stylesheet" type="text/css" href="{% static 'css/candidate-main.css' %}">
<div class="main-module">
    {% include 'basic/vacancy/vacancy-card.html' with vacancy=candidate.vacancy %}
    <div class="main-info">
        <form method="post" action="/candidate-period/{{ candidate.id }}">
            {% csrf_token %}
        {% if not user.is_Customer %}
        <div>

        <select name="id" class="panel-select vacancy">
            {% if  id %}
                <option value="{{ candidate.vacancy.id }}">{{candidate.vacancy.name}}</option>
            {% else %}
                <option value="">Поиск по вакансиям</option>
            {% endif %}
            {% for vacancy in vacancies %}
               {% if  candidate.vacancy.id != vacancy.id %}
            <option value={{ vacancy.id }}>{{ vacancy.name }}</option>
                {% endif %}
            {% endfor %}
        </select>
            <button type="submit" name="asign_vacancy" >Назначить вакансию</button>

</div>
            <div>
            <input type="datetime-local" name="deadline_test_task">
            <button type="submit" name="asing_test_task">Отправить ТЗ</button>
            </div>
{% endif %}
        {% if test_task_was_getten %}
          <div>  <label>
                <input type="radio" name="mark_test_task" value="accepted" for="mark1">
                Успешно
            </label>
            <label>
                <input type="radio" name="mark_test_task" value="not_accepted" for="mark2">
                Отказ
            </label>
            <textarea name="comment_test_task"></textarea>
            <button type="submit" name="send_test_task">Оценить ТЗ</button>
            </div>
        {% endif %}
            <div>
            <input type="datetime-local" name="datetime_interview">
            <button type="submit" name="interview">Интервью</button>
                </div>
        <div>
            <label>
                <input type="radio" name="mark_interview" value="accepted">
                Успешно
            </label>
            <label>
                <input type="radio" name="mark_interview" value="not_accepted">
                Отказ
            </label>
            <textarea name="comment_interview"></textarea>
            <button type="submit" name="send_interview">Оценить интревью</button>
        </div>
        <div>
            <button type="submit" name="send_offer">Оффер</button>
            </div>
        <div>
            <button type="submit" name="send_stop">Отказ</button>
            </div>
        </form>
    </div>
</div>

django-autorecruiting-app/autorecruiting/templates/basic/candidate/card-of-candidate.html
{% load static %}
{% load custom_filters %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/candidate-cards.css' %}">
<div class="card-of-candidate">
    <div class="candidate-image-box">
        {% load static %}
        <img src="{% static 'img/candidate-photo.png' %}">
    </div>
    <div class="candidate-info">
        <div class="candidate-name">{{ candidate.surname }} {{ candidate.name }} {{ candidate.patronymic }}</div>
        <div class="candidate-age">
            <span>Возраст: </span>
            <span>{{ candidate.birthdayDate|display_age }}</span>
        </div>
        <dt>Локация:</dt>
            <dd>{{ candidate.city.cityName}}, {{ candidate.city.country.countryName}}</dd>
        <div class="candidate-experience">
            <span>Опыт работы: </span>
            <span>{{ candidate.workExperienceDuration|display_months }}</span>
        </div>
    </div>
    <div class="candidate-date-of-update">
       Обновлено 3 дня назад
    </div>
    <div class="candidate-more">
        <a href="/candidate-information/main/{{ candidate.id }}">Подробнее</a>
    </div>
</div>

django-autorecruiting-app/autorecruiting/templates/basic/candidate/profile-candidate.html
{% load static %}
{% load custom_filters %}
<link rel="stylesheet" type="text/css" href="{% static 'css/hr-page/profile-panel.css' %}">

<div class="profile-panel">
    <div class="profile-card">
         <div class="profile-image-box">
        {% load static %}
        <img src="{% static 'img/candidate-photo.png' %}">
        </div>
        <div class="candidate-info">
            <div class="candidate-name"> {{ candidate.surname }} {{ candidate.name }} {{ candidate.patronymic }} </div>
            <div class="vacancy-desc">
            <div>
                <div><span>Статус кандидата</span>
                <span>
                    {{ candidate.get_status_display }}
                </span></div>
                <div><span>Почта</span>
                    <span>{{ candidate.email }}</span>
                </div>
                <div><span>Номер</span>
                    <span>{{ candidate.phone }}</span>
                </div>
                <div><span>Возраст</span>
                <span>
                    {{ candidate.birthdayDate|display_age }}</span></div>

                <div><span>Образование</span>
                <span>
                    {{ candidate.get_educationLevel_display }}
                </span></div>
                <div><span>Опыт работы</span>
                <span>
                    {{ candidate.workExperienceDuration|display_months }}
                </span></div>
            <div>
                <span>Готовность к переезду</span>
                <span>
                    {% if candidate.relocationReady == True %}Да
                    {% else %}Нет
                    {% endif %}
                </span>
            </div>
                <div> <span>Ожидаемая зарплата</span>

                    <span>{{ candidate.expectedSalaryFrom }} - {{ candidate.expectedSalaryTo }}
                </span></div>
              <div><span>Специальность</span>


                    <span>{{ candidate.speciality.specialityName }}</span>
                </div>

            </div>
            <a download href="{{ candidate.resumeLink }}">Скачать резюме</a>
        </div>

</div>
    </div>
    <div class="profile-panel-manage">
        <a href="/candidate-information/main/{{ candidate.id }}"><div>Основная информация</div></a>
        <a href="/hr/messenger/candidate/{{ candidate.id }}"><div>Написать</div></a>
        <a href="{% static 'img/candidate-photo.png' %}" download><div>Скачать резюме</div></a>
    </div>
</div>